const TOGGLE_APP_LOADING = 'TOGGLE_APP_LOADING';
const RESET_APP_LOADING = 'RESET_APP_LOADING';

const USER_ACTIONS = {
  UPDATE_LOGIN_STATE: 'UPDATE_LOGIN_STATE',
  SET_USER_PROFILE: 'SET_USER_PROFILE',
};

export default {
  USER_ACTIONS,
  TOGGLE_APP_LOADING,
  RESET_APP_LOADING,
};
